"""
AML Alert Models

Defines data structures for AML alerts generated by transaction monitoring.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field
from uuid import UUID, uuid4


class AlertSeverity(str, Enum):
    """Alert severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """Alert workflow status"""
    NEW = "new"
    ASSIGNED = "assigned"
    UNDER_REVIEW = "under_review"
    ESCALATED = "escalated"
    CLOSED_FALSE_POSITIVE = "closed_false_positive"
    CLOSED_TRUE_POSITIVE = "closed_true_positive"
    SAR_FILED = "sar_filed"


class AlertType(str, Enum):
    """Types of AML alerts"""
    STRUCTURING = "structuring"
    RAPID_MOVEMENT = "rapid_movement"
    HIGH_RISK_GEOGRAPHY = "high_risk_geography"
    UNUSUAL_PATTERN = "unusual_pattern"
    SANCTIONS_HIT = "sanctions_hit"
    PEP_TRANSACTION = "pep_transaction"
    LAYERING = "layering"
    SMURFING = "smurfing"
    ROUND_TRIPPING = "round_tripping"
    CASH_INTENSIVE = "cash_intensive"
    DORMANT_ACCOUNT_ACTIVITY = "dormant_account_activity"
    VELOCITY_BREACH = "velocity_breach"
    AMOUNT_THRESHOLD = "amount_threshold"
    DEVIATION_FROM_PROFILE = "deviation_from_profile"


class AlertTrigger(BaseModel):
    """Details about what triggered an alert"""
    rule_id: str
    rule_name: str
    rule_version: str
    triggered_at: datetime
    threshold_value: Optional[float] = None
    actual_value: Optional[float] = None
    deviation_percentage: Optional[float] = None
    contributing_transactions: List[str] = Field(default_factory=list)


class AlertEvidence(BaseModel):
    """Evidence supporting an alert"""
    evidence_id: UUID = Field(default_factory=uuid4)
    evidence_type: str
    description: str
    data: Dict[str, Any] = Field(default_factory=dict)
    source_system: str
    collected_at: datetime = Field(default_factory=datetime.utcnow)
    collected_by: Optional[str] = None


class AlertComment(BaseModel):
    """Comments on an alert during investigation"""
    comment_id: UUID = Field(default_factory=uuid4)
    author_id: str
    author_name: str
    content: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_internal: bool = True
    attachments: List[str] = Field(default_factory=list)


class AlertAssignment(BaseModel):
    """Alert assignment history"""
    assignment_id: UUID = Field(default_factory=uuid4)
    assigned_to: str
    assigned_by: str
    assigned_at: datetime = Field(default_factory=datetime.utcnow)
    reason: Optional[str] = None
    team: Optional[str] = None


class AMLAlert(BaseModel):
    """Main AML Alert entity"""
    alert_id: UUID = Field(default_factory=uuid4)
    alert_number: str
    alert_type: AlertType
    severity: AlertSeverity
    status: AlertStatus = AlertStatus.NEW

    # Subject information
    customer_id: str
    account_ids: List[str] = Field(default_factory=list)

    # Alert details
    title: str
    description: str
    risk_score: float = Field(ge=0, le=100)

    # Trigger information
    triggers: List[AlertTrigger] = Field(default_factory=list)

    # Related transactions
    transaction_ids: List[str] = Field(default_factory=list)
    total_transaction_amount: float = 0.0
    transaction_count: int = 0
    date_range_start: Optional[datetime] = None
    date_range_end: Optional[datetime] = None

    # Evidence and investigation
    evidence: List[AlertEvidence] = Field(default_factory=list)
    comments: List[AlertComment] = Field(default_factory=list)

    # Assignment and workflow
    assignments: List[AlertAssignment] = Field(default_factory=list)
    current_assignee: Optional[str] = None

    # Case linkage
    case_id: Optional[UUID] = None
    related_alerts: List[UUID] = Field(default_factory=list)

    # SAR information
    sar_required: bool = False
    sar_id: Optional[UUID] = None

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None
    due_date: Optional[datetime] = None

    # Metadata
    source_system: str = "transaction_monitoring"
    tags: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AlertSummary(BaseModel):
    """Summarized view of an alert for listings"""
    alert_id: UUID
    alert_number: str
    alert_type: AlertType
    severity: AlertSeverity
    status: AlertStatus
    customer_id: str
    customer_name: Optional[str] = None
    risk_score: float
    created_at: datetime
    due_date: Optional[datetime] = None
    current_assignee: Optional[str] = None
    transaction_count: int
    total_amount: float


class AlertStatistics(BaseModel):
    """Alert statistics for dashboards"""
    total_alerts: int = 0
    by_severity: Dict[str, int] = Field(default_factory=dict)
    by_status: Dict[str, int] = Field(default_factory=dict)
    by_type: Dict[str, int] = Field(default_factory=dict)
    average_resolution_time_hours: float = 0.0
    false_positive_rate: float = 0.0
    sar_filing_rate: float = 0.0
    overdue_count: int = 0
    assigned_count: int = 0
    unassigned_count: int = 0


class AlertCreateRequest(BaseModel):
    """Request model for creating an alert"""
    alert_type: AlertType
    severity: AlertSeverity
    customer_id: str
    account_ids: List[str] = Field(default_factory=list)
    title: str
    description: str
    risk_score: float = Field(ge=0, le=100)
    transaction_ids: List[str] = Field(default_factory=list)
    triggers: List[AlertTrigger] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)


class AlertUpdateRequest(BaseModel):
    """Request model for updating an alert"""
    status: Optional[AlertStatus] = None
    severity: Optional[AlertSeverity] = None
    current_assignee: Optional[str] = None
    sar_required: Optional[bool] = None
    due_date: Optional[datetime] = None
    tags: Optional[List[str]] = None


class AlertSearchCriteria(BaseModel):
    """Search criteria for alerts"""
    alert_types: Optional[List[AlertType]] = None
    severities: Optional[List[AlertSeverity]] = None
    statuses: Optional[List[AlertStatus]] = None
    customer_ids: Optional[List[str]] = None
    assignees: Optional[List[str]] = None
    date_from: Optional[datetime] = None
    date_to: Optional[datetime] = None
    min_risk_score: Optional[float] = None
    max_risk_score: Optional[float] = None
    tags: Optional[List[str]] = None
    overdue_only: bool = False
    unassigned_only: bool = False
    page: int = 1
    page_size: int = 50
    sort_by: str = "created_at"
    sort_order: str = "desc"
