apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintech-services
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: fintech-services
      containers:
        - name: auth-service
          image: fintech-services/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "auth-service"
            - name: SERVICE_HOST
              value: "0.0.0.0"
            - name: SERVICE_PORT
              value: "8001"
            - name: SERVICE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: LOG_LEVEL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: JWT_SECRET_KEY
            - name: AUTH_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: AUTH_SERVICE_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fintech-services
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
  clusterIP: None  # Headless service for direct pod access
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: fintech-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
